---
- name: Add web server to Zabbix
  hosts: localhost
  gather_facts: no
  vars:
    zabbix_api_url: "http://10.0.10.7/zabbix/api_jsonrpc.php"
    http_login_user: "Admin"
    http_login_password: "Zabbix"
    webserver_ip: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
    webserver_name: "{{ inventory_hostname }}"
    zabbix_host_group: "Web Servers"
    zabbix_template: "Template OS Linux"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: false  # Set to true if using HTTPS
    ansible_httpapi_validate_certs: false  # Change to true if using a valid SSL certificate

  tasks:
    - name: Set credentials for Zabbix API
      ansible.builtin.set_fact:
        ansible_user: "{{ http_login_user }}"
        ansible_httpapi_pass: "{{ http_login_password }}"

    - name: Create host in Zabbix
      community.zabbix.zabbix_host:
        host_name: "{{ webserver_name }}"
        visible_name: "{{ webserver_name }}"
        host_groups:
          - "{{ zabbix_host_group }}"
        link_templates:
          - "{{ zabbix_template }}"
        interfaces:
          - type: 1  # Agent interface
            main: 1
            useip: 1
            ip: "{{ webserver_ip }}"
            dns: ""
            port: "10050"
      environment:
        ZABBIX_URL: "{{ zabbix_api_url }}"