---
- name: Add web server to Zabbix
  hosts: localhost
  gather_facts: no
  vars:
    zabbix_api_url: "http://10.0.10.7/zabbix/api_jsonrpc.php"
    zabbix_api_token: "82d61674195dbfa3a66607cd17135896454e815ebe92dbfaa82dee5d0ea575e1"  # Voeg hier je Zabbix API-token in
    webserver_ip: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
    webserver_name: "{{ inventory_hostname }}"
    zabbix_host_group: "Web Servers"
    zabbix_template: "Template OS Linux"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: false  # Zet op true als je HTTPS gebruikt
    ansible_httpapi_validate_certs: false  # Zet op true als je een geldig SSL-certificaat gebruikt

  tasks:
    - name: Set Zabbix API token
      ansible.builtin.set_fact:
        ansible_zabbix_auth_key: "{{ zabbix_api_token }}"

    - name: Create host in Zabbix using API token
      community.zabbix.zabbix_host:
        url: "http://10.0.10.7/zabbix/api_jsonrpc.php"
        host_name: "{{ webserver_name }}"
        visible_name: "{{ webserver_name }}"
        host_groups:
          - "{{ zabbix_host_group }}"
        link_templates:
          - "{{ zabbix_template }}"
        interfaces:
          - type: 1  # Agent interface
            main: 1
            useip: 1
            ip: "{{ webserver_ip }}"
            dns: ""
            port: "10050"
