---
- name: Add web server to Zabbix
  hosts: localhost
  gather_facts: no
  vars:
    zabbix_api_token: "82d61674195dbfa3a66607cd17135896454e815ebe92dbfaa82dee5d0ea575e1"
    webserver_ip: "{{ webserver_ip }}"
    webserver_name: "{{ webserver_name }}"
    zabbix_host_group: "Linux servers"
    zabbix_template: "Template OS Linux"

  tasks:
    - name: Debug variables
      debug:
        msg: "Webserver IP: {{ webserver_ip }}, Webserver Name: {{ webserver_name }}"

    - name: Set Zabbix API token and URL
      ansible.builtin.set_fact:
        ansible_zabbix_auth_key: "{{ zabbix_api_token }}"
        ansible_zabbix_url: "http://10.0.10.7/zabbix/api_jsonrpc.php"

    - name: Create host in Zabbix using API token
      community.zabbix.zabbix_host:
        state: present
        host_name: "{{ webserver_name }}"
        visible_name: "{{ webserver_name }}"
        host_groups:
          - "{{ zabbix_host_group }}"
        link_templates:
          - "{{ zabbix_template }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ webserver_ip }}"
            dns: ""
            port: "10050"
      environment:
        ZABBIX_URL: "{{ ansible_zabbix_url }}"
        ZABBIX_AUTH: "{{ ansible_zabbix_auth_key }}"
      register: zabbix_host_result

    - debug:
        var: zabbix_host_result
