---
- name: Configure Ubuntu Server (Enable SSH and Open Port 22)
  hosts: all
  become: yes
  vars:
    ansible_user: "student"
    ansible_ssh_pass: "student"
    ansible_become_pass: "student"

  tasks:
    - name: Install SSH
      apt:
        name: openssh-server
        state: present

    - name: Open port 22 for SSH in the firewall
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Ensure SSH is started and enabled on boot
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Update APT repository and cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install Apache Web Server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a simple index.html file for the Apache web server
      copy:
        content: |
          <html>
          <head><title>Welcome to My Web Server</title></head>
          <body><h1>Hello from my Apache Web Server</h1></body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Open port 80 for Apache in the firewall
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
