---
- name: Upgrade Ubuntu Server and Install Apache Web Server
  hosts: all
  become: yes
  vars:
    ansible_user: "{{ ssh_user }}"  # Haal SSH-gebruiker op uit variabelen
    ansible_ssh_pass: "{{ ssh_user_password }}"  # Haal wachtwoord op uit variabelen
    ansible_become_pass: "{{ ssh_user_password }}"  # Wachtwoord voor sudo
  
  tasks:
    - name: Zorg ervoor dat OpenSSH is geïnstalleerd
      apt:
        name: openssh-server
        state: present
        update_cache: yes
  
    - name: Zorg ervoor dat SSH is gestart en ingeschakeld bij opstarten
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Sta SSH-verkeer toe via de firewall
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Update APT repository and cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install Apache Web Server
      apt:
        name: apache2
        state: present
      register: apache_installed

    - name: Ensure Apache service is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a simple index.html file for the Apache web server
      copy:
        content: |
          <html>
          <head><title>Welcome to My Web Server</title></head>
          <body><h1>Hello from my Apache Web Server</h1></body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Open port 80 for Apache in the firewall
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
      when: apache_installed is succeeded

    - name: Ensure Apache is enabled at boot
      service:
        name: apache2
        enabled: yes
