---
- name: Deploy index.html to web servers
  hosts: "{{ target_environment }}"
  become: yes

  tasks:
    - name: Copy index.html to the web server
      copy:
        src: "{{ html_src }}"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
