---
- name: Install and configure Zabbix Agent
  hosts: all
  become: yes
  tasks:
    - name: Add Zabbix repository
      apt:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu $(lsb_release -sc) main"
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=10.0.10.7'
      notify: restart zabbix-agent

    - name: Set Zabbix server active checks
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=10.0.10.7'
      notify: restart zabbix-agent

    - name: Set Hostname for Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
