---
- name: Install and configure Zabbix Agent
  hosts: 10.0.10.110
  become: yes
  tasks:

    - name: Add Zabbix repository GPG key
      apt_key:
        url: 'https://repo.zabbix.com/zabbix-official-repo.key'
        state: present

    - name: Add Zabbix repository
      apt_repository:
        repo: 'deb http://repo.zabbix.com/zabbix/7.0/ubuntu {{ ansible_distribution_release }} main'
        state: present
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=10.0.10.7'
      notify: restart zabbix-agent

    - name: Set Zabbix server active checks
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=10.0.10.7'
      notify: restart zabbix-agent

    - name: Set Hostname for Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
