vsphere_datacenter = "Netlab-DC"
vsphere_resource_pool = "I483725"
vsphere_datastore = "NIM01-I3-DB"
vsphere_network = "2718_I483725_PVlanA"
vsphere_virtual_machine_template = "template_ubuntu_server_ssh"
vsphere_virtual_machine_name = "web-server"
vsphere_folder_path = "_Courses/I3-DB01/I483725/Automation"