vsphere_datacenter = "Netlab-DC"
vsphere_resource_pool = "I483725"
vsphere_datastore = "NIM01-I3-DB"
#vsphere_compute_cluster = "Netlab-Cluster-B"
vsphere_network = "2718_I483725_PVlanA"
vsphere_virtual_machine_template = "Templ_Ubuntu-Linux_Server_22.04.4"
vsphere_virtual_machine_name = "TF_cloned_machine"
vsphere_folder_path = "_Courses/I3-DB01/I483725/TFcloneFolder2"