---
- name: Onboarding new employee
  hosts: windows
  vars:
    employee_password: "SecurePassword123!"
    display_name: "{{ given_name }} {{ middle_name | default('') }} {{ last_name }}"
    employee_name: "{{ given_name | lower }}.{{ last_name | lower }}"
    department_group: "{{ department }}"
    ou_path: "OU={{ department }},OU=Departments,DC=melmel,DC=local"
  tasks:
    - name: Create new AD user in correct OU using PowerShell
      win_shell: |
        $password = ConvertTo-SecureString -AsPlainText -Force "{{ employee_password }}"
        New-ADUser -Name "{{ display_name }}" `
                   -GivenName "{{ given_name }}" `
                   -Surname "{{ last_name }}" `
                   -SamAccountName "{{ employee_name }}" `
                   -UserPrincipalName "{{ employee_name }}@melmel.local" `
                   -AccountPassword $password `
                   -PasswordNeverExpires $true `
                   -Enabled $true `
                   -Description "New employee in {{ department }}" `
                   -Path "{{ ou_path }}"

    - name: Add user to department-specific group using PowerShell
      win_shell: |
        if (Get-ADGroup -Identity "{{ department_group }}" -ErrorAction SilentlyContinue) {
            Add-ADGroupMember -Identity "{{ department_group }}" -Members "{{ employee_name }}"
            Write-Host "User {{ employee_name }} successfully added to group {{ department_group }}"
        } else {
            Write-Host "Group {{ department_group }} does not exist."
        }

- name: Deploy VM for new user
  hosts: localhost
  vars:
    employee_name: "{{ given_name | lower }}.{{ last_name | lower }}"
    department: "{{ department }}"
  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "192.168.200.24"
        username: "I483725@fontysict.nl"
        password: "DF242hv[!"
        validate_certs: False
        datacenter: "Netlab-DC"
        datastore: "DataCluster-Students"
        folder: "/_Courses/I3-DB01/I483725/Orchestration"
        template: "Win10"
        name: "{{ employee_name }}"
        state: "powered-on"
        wait_for_ip_address: true
        resource_pool: "I483725"
      register: vm_info

    - name: Set VM DNS name in vSphere
      community.vmware.vmware_guest_customization:
        hostname: "192.168.200.24"
        username: "I483725@fontysict.nl"
        password: "DF242hv[!"
        validate_certs: False
        datacenter: "Netlab-DC"
        folder: "/_Courses/I3-DB01/I483725/Orchestration"
        name: "{{ employee_name }}"
        customization:
          hostname: "{{ employee_name }}"
          domain: "melmel.local"
          network:
            - dns_servers: ["192.168.60.100"]
              dns_suffix_list: ["melmel.local"]
        when: vm_info.changed

    - name: Reboot VM in vSphere
      community.vmware.vmware_guest_powerstate:
        hostname: "192.168.200.24"
        username: "I483725@fontysict.nl"
        password: "DF242hv[!"
        validate_certs: False
        state: rebooted
        datacenter: "Netlab-DC"
        folder: "/_Courses/I3-DB01/I483725/Orchestration"
        name: "{{ employee_name }}"
        when: vm_info.changed

    - name: Install department-specific software
      win_shell: |
        if ("{{ department }}" -eq "IT department") {
          Start-Process -FilePath "\\192.168.60.100\SoftwareShare\Wireshark-win64-4.0.17.msi" -ArgumentList "/silent" -Wait
        } elseif ("{{ department }}" -eq "HR department") {
          Start-Process -FilePath "\\192.168.60.100\SoftwareShare\googlechromestandaloneenterprise64.msi" -ArgumentList "/silent" -Wait
        }
      delegate_to: "{{ vm_info.instance.ip_address }}"
