---
- name: Onboarding new employee
  hosts: windows
  vars:
    employee_password: "SecurePassword123!"  # Je kunt dit wachtwoord aanpassen naar wens.
    display_name: "{{ given_name }} {{ middle_name | default('') }} {{ last_name }}"
    employee_name: "{{ given_name | lower }}.{{ last_name | lower }}"
    department_group: "{{ department }}"
  tasks:
    - name: Create new AD user
      ansible.windows.win_domain_user:
        name: "{{ employee_name }}"
        user_password: "{{ employee_password }}"
        state: present
        password_never_expires: yes
        given_name: "{{ given_name }}"
        surname: "{{ last_name }}"
        display_name: "{{ display_name }}"
        description: "New employee in {{ department }}"
        groups:
          - "{{ department_group }}"

    - name: Add user to department-specific group
      ansible.windows.win_group_membership:
        name: "{{ department_group }}"
        members:
          - "{{ employee_name }}"
        state: present

    #- name: Install department-specific software
    #  ansible.windows.win_package:
    #    path: "\\\\path\\to\\software_installer.exe"  # Pas dit pad aan naar de locatie van je installer.
    #    arguments: "/silent"
    #    state: present
