---
- name: Onboarding new employee
  hosts: windows
  vars:
    employee_password: "SecurePassword123!"
    display_name: "{{ given_name }} {{ middle_name | default('') }} {{ last_name }}"
    employee_name: "{{ given_name | lower }}.{{ last_name | lower }}"
    department_group: "{{ department }}"
    ou_path: "OU={{ department }},OU=Departments,DC=melmel,DC=local"
  
  tasks:
    - name: Create new AD user in correct OU using PowerShell
      win_shell: |
        $password = ConvertTo-SecureString -AsPlainText -Force "{{ employee_password }}"
        New-ADUser -Name "{{ display_name }}" `
                   -GivenName "{{ given_name }}" `
                   -Surname "{{ last_name }}" `
                   -SamAccountName "{{ employee_name }}" `
                   -UserPrincipalName "{{ employee_name }}@melmel.local" `
                   -AccountPassword $password `
                   -PasswordNeverExpires $true `
                   -Enabled $true `
                   -Description "New employee in {{ department }}" `
                   -Path "{{ ou_path }}"

    - name: Add user to department-specific group using PowerShell
      win_shell: |
        if (Get-ADGroup -Identity "{{ department_group }}" -ErrorAction SilentlyContinue) {
            Add-ADGroupMember -Identity "{{ department_group }}" -Members "{{ employee_name }}"
            Write-Host "User {{ employee_name }} successfully added to group {{ department_group }}"
        } else {
            Write-Host "Group {{ department_group }} does not exist."
        }

    - name: Deploy VM for new user
      community.vmware.vmware_guest:
        hostname: "vcenter.netlab.fontysict.nl"
        username: "i483725@student.fontys.nl"
        password: "DF242hv[!"
        validate_certs: no
        datacenter: "Netlab-DC"
        folder: "/_Courses/I3-DB01/I483725/Orchestration"  # Folder where the VM will be created
        #cluster: "NIM01-I3-DB"
        template: "/_Courses/I3-DB01/I483725/Orchestration/Win10"  # Path to your VM template
        name: "{{ employee_name }}-VM"
        power_on: yes
        networks:
          - name: "2719_I483725_PVlanB"
            type: "dhcp"
        disk:
          - size_gb: 50
            type: "thin"
            datastore: "NIM01-I3-DB"
        hardware:
          memory_mb: 4096
          num_cpus: 2

    - name: Wait for VM to boot and get an IP address
      wait_for:
        host: "{{ employee_name }}-VM"
        port: 5985
        timeout: 300

    - name: Add VM to inventory
      add_host:
        name: "{{ employee_name }}-VM"
        groups: windows

    - name: Install department-specific software
      win_shell: |
        if ("{{ department }}" -eq "IT department") {
          Start-Process -FilePath "\\192.168.60.100\SoftwareShare\Wireshark-win64-4.0.17.msi" -ArgumentList "/silent" -Wait
        } elseif ("{{ department }}" -eq "HR department") {
          Start-Process -FilePath "\\192.168.60.100\SoftwareShare\googlechromestandaloneenterprise64.msi" -ArgumentList "/silent" -Wait
        }
