---
- name: Onboarding new employee
  hosts: windows
  
  tasks:
    - name: Deploy VM
      community.vmware.vmware_guest:
        hostname: "192.168.200.24"
        username: "i483725@student.fontys.nl"
        password: "DF242hv[!"
        validate_certs: False
        name: "Test-VM"
        template: "/_Courses/I3-DB01/I483725/Win10"
        datacenter: "Netlab-DC"
        folder: "/_Courses/I3-DB01/I483725/Orchestration"
        state: "poweredon"
        wait_for_ip_address: no
