---
- name: Onboarding new employee
  hosts: localhost
  
  tasks:
    - name: Deploy VM
      vmware_guest:
        hostname: "192.168.200.24"
        username: "I483725@fontysict.nl"
        password: "DF242hv[!"
        validate_certs: False
        name: "Test-VM"
        template: "Win10" #"/_Courses/I3-DB01/I483725/Orchestration/Win10"
        datacenter: "Netlab-DC"
        datastore: "DataCluster-Students"
        folder: "/_Courses/I3-DB01/I483725/Orchestration"
        resource_pool: "I483725"
        state: "poweredon"
        wait_for_ip_address: no